# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66b0ec40607e6b407106f7757c7a432d52bb45407ce0ed27d48a1667e63c0d9e04e6ed0602dcb60a17f0572be915ed88d453931cf3c5015399b46bd50680e6f1

test:
  secret_key_base: 1e702abcf03d1e17dcb7606f18fe83d8bbea9b770a8f66bd65b8a2e4e6b1bd21901ab045b6518b753b9f59f3a4968677ff8506066c53f0cb07d0d4d2514fcc4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
